version: "3"
services:
  jira-plugin:
    container_name: jira-plugin
    ####################################################################
    # Builds the current code in your repo
    ####################################################################
    build: .
    environment:
      - PLUGIN_VERSION=1.2
      - CONNENCT_JSON_URL=https://integration.invisionapp.com/atlassian-connect.json
      #- CONNENCT_JSON_URL=https://v7.shared.invision.works/jira/atlassian-connect.json
      - CI_COMMIT_ID=loc
    command: "./start.sh"
    ####################################################################
    # Maps port 80 from the container to 8080 on your host, this allows
    # you to access your service via http://localhost:8080.  While we've
    # provided this example here, it's intended as a tool for debugging
    # purposes and not as a permanent bypass for the edge-gateway.
    ####################################################################
    volumes:
      - ./build:/usr/src/app/build
      - ./src:/usr/src/app/src
    ####################################################################
    # Maps your current directory to the jira-bff-v7 directory in the running
    # docker container.  In theory this would allow for you to use a
    # live-reload solution
    ####################################################################
